package Nacionalidades;

public enum Country {
    AFG("AFG", "AF", "Afganistan"),
    ZAF("ZAF", "ZA", "Sudafrica"),
    ALB("ALB", "AL", "Albania"),
    DEU("DEU", "DE", "Alemania"),
    AND("AND", "AD", "Andorra"),
    AGO("AGO", "AO", "Angola"),
    AIA("AIA", "AI", "Anguila"),
    ATA("ATA", "AQ", "Antartida"),
    ATG("ATG", "AG", "Antigua y Barbuda"),
    ANT("ANT", "AN", "Antillas Neerlandesas"),
    SAU("SAU", "SA", "Arabia Saudita"),
    DZA("DZA", "DZ", "Argelia"),
    ARG("ARG", "AR", "Argentina"),
    ARM("ARM", "AM", "Armenia"),
    ABW("ABW", "AW", "Aruba"),
    AUS("AUS", "AU", "Australia"),
    AUT("AUT", "AT", "Austria"),
    AZE("AZE", "AZ", "Azerbaiyan"),
    BHS("BHS", "BS", "Bahamas"),
    BHR("BHR", "BH", "Barein"),
    BGD("BGD", "BD", "Bangladesh"),
    BRB("BRB", "BB", "Barbados"),
    BLR("BLR", "BY", "Bielorrusia"),
    BEL("BEL", "BE", "Belgica"),
    BLZ("BLZ", "BZ", "Belice"),
    BEN("BEN", "BJ", "Benin"),
    BMU("BMU", "BM", "Bermudas"),
    BOL("BOL", "BO", "Bolivia"),
    BIH("BIH", "BA", "Bosnia y Herzegovina"),
    BWA("BWA", "BW", "Botsuana"),
    BRA("BRA", "BR", "Brasil"),
    BRN("BRN", "BN", "Brunei"),
    BGR("BGR", "BG", "Bulgaria"),
    BFA("BFA", "BF", "Burkina Faso"),
    BDI("BDI", "BI", "Burundi"),
    BTN("BTN", "BT", "Butan"),
    CPV("CPV", "CV", "Cabo Verde"),
    CMR("CMR", "CM", "Camerun"),
    KHM("KHM", "KH", "Camboya"),
    CAN("CAN", "CA", "Canada"),
    KAZ("KAZ", "KZ", "Kazajistan"),
    TCD("TCD", "TD", "Chad"),
    CHL("CHL", "CL", "Chile"),
    CHN("CHN", "CN", "China"),
    CYP("CYP", "CY", "Chipre"),
    SGP("SGP", "SG", "Singapur"),
    COL("COL", "CO", "Colombia"),
    COG("COG", "CG", "Congo"),
    PRK("PRK", "KP", "Corea del Norte"),
    KOR("KOR", "KR", "Corea del Sur"),
    CIV("CIV", "CI", "Costa de Marfil"),
    CRI("CRI", "CR", "Costa Rica"),
    HRV("HRV", "HR", "Croacia"),
    CUB("CUB", "CU", "Cuba"),
    DNK("DNK", "DK", "Dinamarca"),
    DJI("DJI", "DJ", "Djibuti"),
    DMA("DMA", "DM", "Dominica"),
    EGY("EGY", "EG", "Egipto"),
    SLV("SLV", "SV", "El Salvador"),
    ARE("ARE", "AE", "Emiratos Arabes Unidos"),
    ECU("ECU", "EC", "Ecuador"),
    ERI("ERI", "ER", "Eritrea"),
    SVK("SVK", "SK", "Eslovaquia"),
    SVN("SVN", "SI", "Eslovenia"),
    ESP("ESP", "ES", "España"),
    USA("USA", "US", "Estados Unidos"),
    EST("EST", "EE", "Estonia"),
    ETH("ETH", "ET", "Etiopia"),
    FJI("FJI", "FJ", "Fiji"),
    PHL("PHL", "PH", "Filipinas"),
    FIN("FIN", "FI", "Finlandia"),
    FRA("FRA", "FR", "Francia"),
    GAB("GAB", "GA", "Gabon"),
    GMB("GMB", "GM", "Gambia"),
    GHA("GHA", "GH", "Ghana"),
    GEO("GEO", "GE", "Georgia"),
    GIB("GIB", "GI", "Gibraltar"),
    GBR("GBR", "GB", "Gran Bretanña"),
    GRD("GRD", "GD", "Granada"),
    GRC("GRC", "GR", "Grecia"),
    GRL("GRL", "GL", "Groelandia"),
    GLP("GLP", "GP", "Guadalupe"),
    GUM("GUM", "GU", "Guam"),
    GTM("GTM", "GT", "Guatemala"),
    GGY("GGY", "G", "Guernsey"),
    GUY("GUY", "GY", "Guyana"),
    GUF("GUF", "GF", "Guyana Francesa"),
    GIN("GIN", "GN", "Guinea"),
    GNQ("GNQ", "GQ", "Guinea Ecuatorial"),
    GNB("GNB", "GW", "Guinea-Bisau"),
    HTI("HTI", "HT", "Haiti"),
    NLD("NLD", "NL", "Paises Bajos"),
    HND("HND", "HN", "Honduras"),
    HKG("HKG", "HK", "Hong Kong"),
    HUN("HUN", "HU", "Hungria"),
    YEM("YEM", "YE", "Yemen"),
    BVT("BVT", "BV", "Isal Bouvet"),
    IMN("IMN", "IM", "Isla del Hombre"),
    CXR("CXR", "CX", "Isla de Navidad"),
    PCN("PCN", "PN", "Isla Pitcairn"),
    REU("REU", "RE", "Isla Reunion"),
    ALA("ALA", "AX", "Islas Aland"),
    CYM("CYM", "KY", "Islas Caiman"),
    CCK("CCK", "CC", "Islas Cocos"),
    COM("COM", "KM", "Islas Comoras"),
    COK("COK", "CK", "Islas Cook"),
    FRO("FRO", "FO", "Islas Faroe"),
    FLK("FLK", "FK", "Ilhas Malvinas"),
    SGS("SGS", "GS", "Islas Georgia del Sur y Sandwich del Sur"),
    HMD("HMD", "HM", "Islas Heard y McDonald"),
    MNP("MNP", "MP", "Islas Marianas del Norte"),
    MHL("MHL", "MH", "Islas Marshall"),
    UMI("UMI", "UM", "Islas Menores de Estados Unidos"),
    NFK("NFK", "NF", "Islas Norfolk"),
    SYC("SYC", "SC", "Seychelles"),
    SLB("SLB", "SB", "Islas Solomon"),
    SJM("SJM", "SJ", "Islas Svalbard y Jan Mayen"),
    TKL("TKL", "TK", "Islas Tokelau"),
    TCA("TCA", "TC", "Islas Turcais y Caicos"),
    VIR("VIR", "VI", "Islas Virgenes (EEUU)"),
    VGB("VGB", "VG", "Islas Virgenes (Inglaterra)"),
    WLF("WLF", "WF", "Islas Wallis y Fortuna"),
    IND("IND", "IN", "India"),
    IDN("IDN", "ID", "Indonesia"),
    IRN("IRN", "IR", "Iran"),
    IRQ("IRQ", "IQ", "Irak"),
    IRL("IRL", "IE", "Irlanda"),
    ISL("ISL", "IS", "Islandia"),
    ISR("ISR", "IL", "Israel"),
    ITA("ITA", "IT", "Italia"),
    JAM("JAM", "JM", "Jamaica"),
    JPN("JPN", "JP", "Japon"),
    JEY("JEY", "JE", "Jersey"),
    JOR("JOR", "JO", "Jordania"),
    KEN("KEN", "KE", "Kenia"),
    KIR("KIR", "KI", "Kiribati"),
    KWT("KWT", "KW", "Kuwait"),
    LAO("LAO", "LA", "Laos"),
    LVA("LVA", "LV", "Latvia"),
    LSO("LSO", "LS", "Lesoto"),
    LBN("LBN", "LB", "Líbano"),
    LBR("LBR", "LR", "Liberia"),
    LBY("LBY", "LY", "Libia"),
    LIE("LIE", "LI", "Liechtenstein"),
    LTU("LTU", "LT", "Lituania"),
    LUX("LUX", "LU", "Luxemburgo"),
    MAC("MAC", "MO", "Macao"),
    MKD("MKD", "MK", "Macedonia"),
    MDG("MDG", "MG", "Madagascar"),
    MYS("MYS", "MY", "Malasia"),
    MWI("MWI", "MW", "Malaui"),
    MDV("MDV", "MV", "Maldivas"),
    MLI("MLI", "ML", "Mali"),
    MLT("MLT", "MT", "Malta"),
    MAR("MAR", "MA", "Marruecos"),
    MTQ("MTQ", "MQ", "Martinica"),
    MUS("MUS", "MU", "Maurício"),
    MRT("MRT", "MR", "Mauritania"),
    MYT("MYT", "YT", "Mayotte"),
    MEX("MEX", "MX", "Mexico"),
    FSM("FSM", "FM", "Micronesia"),
    MOZ("MOZ", "MZ", "Mozambique"),
    MDA("MDA", "MD", "Moldavia"),
    MCO("MCO", "MC", "Monaco"),
    MNG("MNG", "MN", "Mongolia"),
    MNE("MNE", "ME", "Montenegro"),
    MSR("MSR", "MS", "Montserrat"),
    MMR("MMR", "MM", "Birmania"),
    NAM("NAM", "NA", "Namibia"),
    NRU("NRU", "NR", "Nauru"),
    NPL("NPL", "NP", "Nepal"),
    NIC("NIC", "NI", "Nicaragua"),
    NER("NER", "NE", "Niger"),
    NGA("NGA", "NG", "Nigeria"),
    NIU("NIU", "NU", "Niue"),
    NOR("NOR", "NO", "Noruega"),
    NCL("NCL", "NC", "Nueva Caledonia"),
    NZL("NZL", "NZ", "Nueva Zelanda"),
    OMN("OMN", "OM", "Oman"),
    PLW("PLW", "PW", "Palau"),
    PAN("PAN", "PA", "Panama"),
    PNG("PNG", "PG", "Papua Nueva Guinea"),
    PAK("PAK", "PK", "Paquistan"),
    PRY("PRY", "PY", "Paraguay"),
    PER("PER", "PE", "Peru"),
    PYF("PYF", "PF", "Polinesia Francesa"),
    POL("POL", "PL", "Polonia"),
    PRI("PRI", "PR", "Puerto Rico"),
    PRT("PRT", "PT", "Portugal"),
    QAT("QAT", "QA", "Qatar"),
    KGZ("KGZ", "KG", "Kirguistan"),
    CAF("CAF", "CF", "Republica Centroafricana"),
    COD("COD", "CD", "Republica Democratica del Congo"),
    DOM("DOM", "DO", "Republica Dominicana"),
    CZE("CZE", "CZ", "Republica Checa"),
    ROM("ROM", "RO", "Rumania"),
    RWA("RWA", "RW", "Ruanda"),
    RUS("RUS", "RU", "Rusia"),
    ESH("ESH", "EH", "Sahara Occidental"),
    VCT("VCT", "VC", "San Vincente y las Granadinas"),
    ASM("ASM", "AS", "Samoa Americana"),
    WSM("WSM", "WS", "Samoa Occidental"),
    SMR("SMR", "SM", "San Marino"),
    SHN("SHN", "SH", "Santa Elena"),
    LCA("LCA", "LC", "Santa Lucia"),
    BLM("BLM", "BL", "San Bartolome"),
    KNA("KNA", "KN", "San Cristobal y Nieves"),
    MAF("MAF", "MF", "San Martin"),
    STP("STP", "ST", "Santo Tome y principe"),
    SEN("SEN", "SN", "Senegal"),
    SLE("SLE", "SL", "Sierra Leona"),
    SRB("SRB", "RS", "Serbia"),
    SYR("SYR", "SY", "Siria"),
    SOM("SOM", "SO", "Somalia"),
    LKA("LKA", "LK", "Sri Lanka"),
    SPM("SPM", "PM", "San Pedro y Miquelon"),
    SWZ("SWZ", "SZ", "Esuatini"),
    SDN("SDN", "SD", "Sudan"),
    SWE("SWE", "SE", "Suecia"),
    CHE("CHE", "CH", "Suiza"),
    SUR("SUR", "SR", "Surinam"),
    TJK("TJK", "TJ", "Tayikistan"),
    THA("THA", "TH", "Tailandia"),
    TWN("TWN", "TW", "Taiwan"),
    TZA("TZA", "TZ", "Tanzania"),
    IOT("IOT", "IO", "Territorio Britanico del Oceano Indico"),
    ATF("ATF", "TF", "Territorios del Sur de Francia"),
    PSE("PSE", "PS", "Territorios Palestinos Ocupados"),
    TMP("TMP", "TP", "Timor Leste"),
    TGO("TGO", "TG", "Togo"),
    TON("TON", "TO", "Tonga"),
    TTO("TTO", "TT", "Trinidad y Tobago"),
    TUN("TUN", "TN", "Tunez"),
    TKM("TKM", "TM", "Turcomenistan"),
    TUR("TUR", "TR", "Turquia"),
    TUV("TUV", "TV", "Tuvalu"),
    UKR("UKR", "UA", "Ucrania"),
    UGA("UGA", "UG", "Uganda"),
    URY("URY", "UY", "Uruguay"),
    UZB("UZB", "UZ", "Uzbekistan"),
    VUT("VUT", "VU", "Vanuatu"),
    VAT("VAT", "VA", "Vaticano"),
    VEN("VEN", "VE", "Venezuela"),
    VNM("VNM", "VN", "Vietnam"),
    ZMB("ZMB", "ZM", "Zambia"),
    ZWE("ZWE", "ZW", "Zimbabue");

    private String name;
    private String threeDigitsCode;
    private String twoDigitsCode;

    Country(String threeDigitsCode, String twoDigitsCode, String name) {
        this.twoDigitsCode = twoDigitsCode;
        this.threeDigitsCode = threeDigitsCode;
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public String getThreeDigitsCode() {
        return threeDigitsCode;
    }

    public String getTwoDigitsCode() {
        return twoDigitsCode;
    }
